server:
  port: 8082

spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://snehaldighore21_db_user:Shubham12345@cloudblitz-cluster.veyytru.mongodb.net/cb_auth?retryWrites=true&w=majority&appName=cloudblitz-cluster}
  security:

logging:
  level:
    in.cloudblitz.course: DEBUG
