server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://snehaldighore21_db_user:Shubham12345@cloudblitz-cluster.veyytru.mongodb.net/cb_auth?retryWrites=true&w=majority&appName=cloudblitz-cluster}
  security:
    user:
      name: admin
      password: admin

jwt:
  secret: ${JWT_SECRET:CloudBlitzJWTSecretKeyForSecureAuthentication2024!@#}
  expiration: 86400000 # 24 hours

logging:
  level:
    in.cloudblitz.auth: DEBUG
